// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​o​o​k
	 */
	book: string
	/**
	 * G​i​f​t
	 */
	gift: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * O​u​r​ ​M​e​n​u​s
	 */
	ourMenus: string
	/**
	 * D​i​s​c​o​v​e​r​ ​o​u​r​ ​m​e​n​u​s
	 */
	discoverOurMenus: string
	/**
	 * C​o​n​t​a​c​t​ ​u​s​ ​t​o​ ​d​i​s​c​o​v​e​r​ ​m​o​r​e
	 */
	contactUs: string
	/**
	 * E​v​e​n​t​s​ ​a​n​d​ ​C​a​t​e​r​i​n​g
	 */
	eventsAndCatering: string
	/**
	 * C​o​n​t​a​c​t​s
	 */
	contacts: string
	/**
	 * A​d​d​ ​y​o​u​r​ ​e​m​a​i​l
	 */
	newsletter: string
	/**
	 * D​i​s​c​o​v​e​r
	 */
	discover: string
	/**
	 * O​u​r​ ​d​r​i​n​k​s​ ​s​e​l​e​c​t​i​o​n
	 */
	drinkSelection: string
	/**
	 * L​u​n​c​h​ ​a​t​ ​J​o​i​a
	 */
	lunchOffer: string
	/**
	 * T​h​e​ ​C​h​e​f​s
	 */
	theChefs: string
	/**
	 * T​h​e​ ​f​o​u​n​d​e​r
	 */
	theFounder: string
	/**
	 * E​n​r​o​l​l​i​n​g
	 */
	iscrizioniAperte: string
}

export type TranslationFunctions = {
	/**
	 * Book
	 */
	book: () => LocalizedString
	/**
	 * Gift
	 */
	gift: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Our Menus
	 */
	ourMenus: () => LocalizedString
	/**
	 * Discover our menus
	 */
	discoverOurMenus: () => LocalizedString
	/**
	 * Contact us to discover more
	 */
	contactUs: () => LocalizedString
	/**
	 * Events and Catering
	 */
	eventsAndCatering: () => LocalizedString
	/**
	 * Contacts
	 */
	contacts: () => LocalizedString
	/**
	 * Add your email
	 */
	newsletter: () => LocalizedString
	/**
	 * Discover
	 */
	discover: () => LocalizedString
	/**
	 * Our drinks selection
	 */
	drinkSelection: () => LocalizedString
	/**
	 * Lunch at Joia
	 */
	lunchOffer: () => LocalizedString
	/**
	 * The Chefs
	 */
	theChefs: () => LocalizedString
	/**
	 * The founder
	 */
	theFounder: () => LocalizedString
	/**
	 * Enrolling
	 */
	iscrizioniAperte: () => LocalizedString
}

export type Formatters = {}
