// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​i​n​ ​e​n​g​l​i​s​h
	 */
	welcome: string
}

export type TranslationFunctions = {
	/**
	 * Hi in english
	 */
	welcome: () => LocalizedString
}

export type Formatters = {}
