// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​o​o​k
	 */
	book: string
	/**
	 * G​i​f​t
	 */
	gift: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * O​u​r​ ​M​e​n​u​s
	 */
	ourMenus: string
	/**
	 * E​v​e​n​t​s​ ​a​n​d​ ​C​a​t​e​r​i​n​g
	 */
	eventsAndCatering: string
	/**
	 * C​o​n​t​a​c​t​s
	 */
	contacts: string
	/**
	 * A​d​d​ ​y​o​u​r​ ​e​m​a​i​l
	 */
	newsletter: string
}

export type TranslationFunctions = {
	/**
	 * Book
	 */
	book: () => LocalizedString
	/**
	 * Gift
	 */
	gift: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Our Menus
	 */
	ourMenus: () => LocalizedString
	/**
	 * Events and Catering
	 */
	eventsAndCatering: () => LocalizedString
	/**
	 * Contacts
	 */
	contacts: () => LocalizedString
	/**
	 * Add your email
	 */
	newsletter: () => LocalizedString
}

export type Formatters = {}
